name: Build and Test Gradle App

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: see working directory
        run: ls; pwd; cd spring_backend; ls; pwd; cd

      - name: Set up JDK 18
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "18"

      - name: Grant execute permissions for gradlew
        run: chmod +x ./gradlew
        working-directory: spring_backend

      - name: Build with Gradle
        run: ./gradlew build
        working-directory: spring_backend

      - name: Run Tests
        run: ./gradlew test
        working-directory: spring_backend

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: spring_backend/build/reports/tests/test/
