name: Build and Test Gradle App

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 18
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "18"

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3

      - name: Build with Gradle
        run: gradle build
        working-directory: spring_backend

      - name: Run Tests
        run: gradle test
        working-directory: spring_backend

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: spring_backend/build/reports/tests/test/
