name: Build and Test Gradle App

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 18
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "18"

      - name: Grant execute permissions for gradlew
        run: chmod +x ~/spring_backend/gradlew

      - name: Build with Gradle
        run: ~/spring_backend/gradlew build

      - name: Run Tests
        run: ~/spring_backend/gradlew test

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: build/reports/tests/test/
