name: Hello World

on:
  push:
    branches:
      - master
      - main
      - dev

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: A job to say hello
        run: echo "Hello, world!"
  spill_some_secrets:
    runs-on: ubuntu-latest
    steps:
      - name: A job to spill some secrets
        run: echo ${{ secrets.MY_SECRET }}
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run script
        run: ./run.sh
