name: Hello World

on:
  push:
    branches:
      - master
      - main
      - dev

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: A job to say hello
        run: echo "Hello, world!"
  spill_some_secrets:
    runs-on: ubuntu-latest
    steps:
      - name: A job to spill some secrets
        run: echo ${{ secrets.MY_SECRET }}

  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Run script
        run: sh run.sh

  connect_ssh:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 2222
          script: echo “Hello World”

  copy_file_via_scp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Copy file via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 2222
          source: "run.sh"
          target: "/tmp/run.sh"

  run_remote_script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run remote script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 2222
          script: |
            chmod +x /tmp/run.sh
            sh /tmp/run.sh
