name: Hello World

on:
  push:
    branches:
      - master
      - main
      - dev

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: A job to say hello
        run: echo "Hello, world!"
